package com.kiwi.common_ui_compose.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006c44)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF8cf8bf)
val md_theme_light_onPrimaryContainer = Color(0xFF002111)
val md_theme_light_secondary = Color(0xFF4e6356)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd0e9d7)
val md_theme_light_onSecondaryContainer = Color(0xFF0b1f15)
val md_theme_light_tertiary = Color(0xFF3c6472)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc0e9f9)
val md_theme_light_onTertiaryContainer = Color(0xFF001f28)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdf8)
val md_theme_light_onBackground = Color(0xFF191c1a)
val md_theme_light_surface = Color(0xFFfbfdf8)
val md_theme_light_onSurface = Color(0xFF191c1a)
val md_theme_light_surfaceVariant = Color(0xFFdce5dc)
val md_theme_light_onSurfaceVariant = Color(0xFF404943)
val md_theme_light_outline = Color(0xFF707972)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1ed)
val md_theme_light_inverseSurface = Color(0xFF2d312e)
val md_theme_light_inversePrimary = Color(0xFF6fdba4)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF6fdba4)
val md_theme_dark_onPrimary = Color(0xFF003921)
val md_theme_dark_primaryContainer = Color(0xFF005232)
val md_theme_dark_onPrimaryContainer = Color(0xFF8cf8bf)
val md_theme_dark_secondary = Color(0xFFb4ccbb)
val md_theme_dark_onSecondary = Color(0xFF203529)
val md_theme_dark_secondaryContainer = Color(0xFF364c3f)
val md_theme_dark_onSecondaryContainer = Color(0xFFd0e9d7)
val md_theme_dark_tertiary = Color(0xFFa4cddd)
val md_theme_dark_onTertiary = Color(0xFF043542)
val md_theme_dark_tertiaryContainer = Color(0xFF234c59)
val md_theme_dark_onTertiaryContainer = Color(0xFFc0e9f9)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1a)
val md_theme_dark_onBackground = Color(0xFFe1e3df)
val md_theme_dark_surface = Color(0xFF191c1a)
val md_theme_dark_onSurface = Color(0xFFe1e3df)
val md_theme_dark_surfaceVariant = Color(0xFF404943)
val md_theme_dark_onSurfaceVariant = Color(0xFFc0c9c1)
val md_theme_dark_outline = Color(0xFF8a938b)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1a)
val md_theme_dark_inverseSurface = Color(0xFFe1e3df)
val md_theme_dark_inversePrimary = Color(0xFF006c44)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF7ae6ae)
val error = Color(0xFFba1b1b)