name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build Mojito AAB
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            ktlintCheck
            bundleRelease

      - name: Sign app AAB
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD }}

      - name: Publish build to internal track
        if: github.ref == 'refs/heads/master'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.kiwi.cocktail
          track: internal
          status: completed
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt